# Generated by Django 5.0.6 on 2026-08-12 07:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourtSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاریخ (میلادی)')),
                ('jalali_date', models.CharField(help_text='مانند: ۱۴۰۳/۱۲/۱۵ یا شنبه ۱۵ اسفند', max_length=50, verbose_name='تاریخ شمسی')),
                ('start_time', models.TimeField(verbose_name='ساعت شروع')),
                ('end_time', models.TimeField(verbose_name='ساعت پایان')),
                ('price', models.PositiveIntegerField(verbose_name='قیمت سانس (تومان)')),
                ('discount_percent', models.PositiveIntegerField(default=0, verbose_name='تخفیف (%)')),
                ('is_booked', models.BooleanField(default=False, verbose_name='رزرو شده')),
                ('is_blocked', models.BooleanField(default=False, verbose_name='مسدود توسط ادمین')),
            ],
            options={
                'verbose_name': 'سانس تقویم',
                'verbose_name_plural': 'سانس\u200cهای تقویم',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='GalleryCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی گالری',
                'verbose_name_plural': 'دسته\u200cبندی\u200cهای گالری',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان اسلاید')),
                ('subtitle', models.CharField(blank=True, max_length=255, verbose_name='زیرعنوان اسلاید')),
                ('image', models.ImageField(upload_to='slides/', verbose_name='تصویر اسلاید')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'اسلاید هیرو',
                'verbose_name_plural': 'اسلایدهای هیرو',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Royal Court', max_length=100, verbose_name='نام مجموعه')),
                ('site_title_fa', models.CharField(default='مجموعه تنیس رویال کورت', max_length=150, verbose_name='عنوان فارسی وبسایت')),
                ('manager_name', models.CharField(default='محمد عتبات', max_length=100, verbose_name='نام مدیریت')),
                ('phone_number', models.CharField(default='021-22001122 | 09121112233', max_length=50, verbose_name='شماره تماس پشتیبانی')),
                ('instagram', models.CharField(default='@royalcourt_tennis', max_length=100, verbose_name='آیدی اینستاگرام')),
                ('address', models.CharField(default='تهران، خیابان فرشته، مجموعه تنیس VIP رویال کورت', max_length=255, verbose_name='آدرس مجموعه')),
                ('hero_title', models.CharField(default='تجربه\u200cای متفاوت در لوکس\u200cترین زمین\u200cهای تنیس خاکی', max_length=200, verbose_name='تیتر اصلی هیرو')),
                ('hero_subtitle', models.TextField(default='زمین\u200cهای تنیس خاکی استاندارد با زیرسازی تخصصی، نورپردازی شبانه، مربیان بین\u200cالمللی و رزرو آنلاین آنی بدون نیاز به ثبت\u200cنام', verbose_name='توضیحات هیرو')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='hero/', verbose_name='تصویر اصلی هیرو')),
                ('about_title', models.CharField(default='درباره آکادمی و مجموعه تنیس رویال کورت', max_length=200, verbose_name='عنوان درباره ما')),
                ('about_text', models.TextField(default='مجموعه ورزشی رویال کورت با مدیریت جناب آقای محمد عتبات، با بهره\u200cگیری از مدرن\u200cترین استانداردهای بین\u200cالمللی فدراسیون جهانی تنیس (ITF)، مجهز به زمین\u200cهای خاکی سرخ استاندارد، سیستم نورپردازی حرفه\u200cای دید در شب، کلاب\u200cهاوس VIP، و کادر آموزشی مجرب آماده خدمت\u200cرسانی به علاقه\u200cمندان تنیس می\u200cباشد.', verbose_name='متن درباره ما')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about/', verbose_name='تصویر درباره ما')),
                ('base_session_price', models.PositiveIntegerField(default=500000, verbose_name='قیمت پایه هر سانس (تومان)')),
                ('default_discount_percent', models.PositiveIntegerField(default=15, verbose_name='درصد تخفیف عمومی (%)')),
                ('price_notice_text', models.CharField(default='⚡ تخفیف ۱۵ درصدی برای تمامی سانس\u200cهای صبحگاهی و آخر هفته به مدت محدود!', max_length=255, verbose_name='متن اطلاع\u200cرسانی بالای تقویم')),
            ],
            options={
                'verbose_name': 'تنظیمات عمومی وبسایت',
                'verbose_name_plural': 'تنظیمات عمومی وبسایت',
            },
        ),
        migrations.CreateModel(
            name='TennisCourt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام زمین')),
                ('court_type', models.CharField(default='تنیس خاکی (Red Clay)', max_length=100, verbose_name='نوع زمین')),
                ('description', models.TextField(blank=True, verbose_name='توضیحات زمین')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'زمین تنیس',
                'verbose_name_plural': 'زمین\u200cهای تنیس',
            },
        ),
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان کلاس آموزشی')),
                ('coach_name', models.CharField(max_length=100, verbose_name='نام مدرس / سرمربی')),
                ('level', models.CharField(default='مبتدی تا پیشرفته', max_length=100, verbose_name='سطح برگزاری')),
                ('duration', models.CharField(default='۱۰ جلسه ۱ ساعته', max_length=100, verbose_name='مدت دوره')),
                ('tuition', models.PositiveIntegerField(verbose_name='شهریه دوره (تومان)')),
                ('schedule_info', models.CharField(default='روزهای زوج و فرد - هماهنگی با ادمین', max_length=200, verbose_name='زمان\u200cبندی کلاس')),
                ('features_list', models.TextField(help_text='هر ویژگی در یک خط جدید وارد شود', verbose_name='ویژگی\u200cهای کلاس')),
                ('image', models.ImageField(blank=True, null=True, upload_to='classes/', verbose_name='تصویر کلاس')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'کلاس آموزشی',
                'verbose_name_plural': 'کلاس\u200cهای آموزشی',
            },
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='عنوان تصویر')),
                ('image', models.ImageField(upload_to='gallery/', verbose_name='تصویر')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح کوتاه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courts.gallerycategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'تصویر گالری',
                'verbose_name_plural': 'گالری تصاویر',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی رزرو کننده')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('tracking_code', models.CharField(max_length=20, unique=True, verbose_name='کد پیگیری رزرو')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت رزرو')),
                ('is_confirmed', models.BooleanField(default=True, verbose_name='تایید شده')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reservation', to='courts.courtslot', verbose_name='سانس رزرو شده')),
            ],
            options={
                'verbose_name': 'رزرو کاربر',
                'verbose_name_plural': 'لیست رزروها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='courtslot',
            name='court',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='courts.tenniscourt', verbose_name='زمین تنیس'),
        ),
        migrations.CreateModel(
            name='ClassEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=20, verbose_name='شماره تماس')),
                ('notes', models.TextField(blank=True, verbose_name='توضیحات تکمیلی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت\u200cنام')),
                ('training_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courts.trainingclass', verbose_name='کلاس آموزشی')),
            ],
            options={
                'verbose_name': 'ثبت\u200cنام کلاس آموزشی',
                'verbose_name_plural': 'ثبت\u200cنام\u200cهای کلاس\u200cهای آموزشی',
            },
        ),
    ]
